CREATE TABLE tipoSangre (
    idTipoSangre INT PRIMARY KEY,
    tipoSangre VARCHAR2(50)
);

INSERT INTO tipoSangre VALUES (1, 'A+');
INSERT INTO tipoSangre VALUES (2, 'A-');
INSERT INTO tipoSangre VALUES (3, 'B+');
INSERT INTO tipoSangre VALUES (4, 'B-');
INSERT INTO tipoSangre VALUES (5, 'AB+');
INSERT INTO tipoSangre VALUES (6, 'AB-');
INSERT INTO tipoSangre VALUES (7, 'O+');
INSERT INTO tipoSangre VALUES (8, 'O-');

CREATE TABLE camas (
    idCama INT PRIMARY KEY
);

INSERT INTO camas (idCama) VALUES (1);
INSERT INTO camas (idCama) VALUES (2);
INSERT INTO camas (idCama) VALUES (3);
INSERT INTO camas (idCama) VALUES (4);
INSERT INTO camas (idCama) VALUES (5);


CREATE TABLE habitaciones (
    idHabitacion INT PRIMARY KEY,
    idCama INT REFERENCES camas(idCama)
);

INSERT INTO habitaciones (idHabitacion, idCama) VALUES (101, 1);
INSERT INTO habitaciones (idHabitacion, idCama) VALUES (102, 2);
INSERT INTO habitaciones (idHabitacion, idCama) VALUES (103, 3);
INSERT INTO habitaciones (idHabitacion, idCama) VALUES (104, 4);
INSERT INTO habitaciones (idHabitacion, idCama) VALUES (105, 5);


CREATE TABLE medicamento (
    idMedicamento INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR2(100),
    descripcion VARCHAR2(200)
);
INSERT INTO medicamento (nombre, descripcion) VALUES ('Paracetamol', 'Analgésico y antipirético');
INSERT INTO medicamento (nombre, descripcion) VALUES ('Ibuprofeno', 'Antiinflamatorio no esteroideo');
INSERT INTO medicamento (nombre, descripcion) VALUES ('Omeprazol', 'Inhibidor de la bomba de protones');
INSERT INTO medicamento (nombre, descripcion) VALUES ('Amoxicilina', 'Antibiótico de amplio espectro');
INSERT INTO medicamento (nombre, descripcion) VALUES ('Atorvastatina', 'Estatina para reducción de colesterol');

select * from medicamento;

CREATE TABLE paciente (
    idPaciente INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombres VARCHAR2(100),
    idTipoSangre INT REFERENCES tipoSangre(idTipoSangre),
    telefono VARCHAR2(20),
    enfermedad VARCHAR2(100),
    idHabitacion INT REFERENCES habitaciones(idHabitacion),
    fechaNacimiento VARCHAR2(50)
);

CREATE TABLE paciente_medicamento (
    idPaciente INT,
    idMedicamento INT,
    horaAplicacion VARCHAR2(50),
    PRIMARY KEY (idPaciente, idMedicamento),
    FOREIGN KEY (idPaciente) REFERENCES paciente(idPaciente),
    FOREIGN KEY (idMedicamento) REFERENCES medicamento(idMedicamento)
);

